name: Docker Build CI

on:
  push:
    branches:
      - master

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: sskender
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build image
        run: docker build --tag sskender/altcoin-mxe:latest .

      - name: Push to DockerHub
        run: docker push sskender/altcoin-mxe:latest
